package raf.dsw.gerumap.gui.swing.error;

public enum ProblemType {
    CANNOT_ADD_CHILD,
    CANNOT_REMOVE_PROJECT_EXPLORER,
    CANNOT_SAVE_PROJECT_EXPLORER,
    NOTHING_IS_SELECTED,
    INVALID_NAME,
    INVALID_TEXT,
    INVALID_CONNECTION,
    CANNOT_SET_AUTHOR,
    POSITION_TAKEN,
    ALREADY_HAS_CONNECTION,
    HAS_TO_BE_ZOOMED
}
